package com.diffblue.demo.ecommerce.forms;

import com.diffblue.demo.ecommerce.forms.AddressForm;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

import java.lang.reflect.Method;

public class AddressFormTest {

  @Rule public ExpectedException thrown = ExpectedException.none();
  @Rule public Timeout globalTimeout = new Timeout(10000);

  /* testedClasses: AddressForm */
  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void constructorOutputVoid() {

    // Act, creating object to test constructor
    final AddressForm objectUnderTest = new AddressForm();

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getAddressLineOutputNull() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();

    // Act
    final String retval = objectUnderTest.getAddressLine();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getCityOutputNull() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();

    // Act
    final String retval = objectUnderTest.getCity();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getCompanyOutputNull() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();

    // Act
    final String retval = objectUnderTest.getCompany();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getCountryOutputNull() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();

    // Act
    final String retval = objectUnderTest.getCountry();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getPostcodeOutputNull() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();

    // Act
    final String retval = objectUnderTest.getPostcode();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setAddressLineInputNotNullOutputVoid() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();
    final String addressLine = "Large";

    // Act
    objectUnderTest.setAddressLine(addressLine);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setCityInputNotNullOutputVoid() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();
    final String city = "Large";

    // Act
    objectUnderTest.setCity(city);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setCompanyInputNotNullOutputVoid() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();
    final String company = "Large";

    // Act
    objectUnderTest.setCompany(company);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setCountryInputNotNullOutputVoid() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();
    final String country = "Large";

    // Act
    objectUnderTest.setCountry(country);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setPostcodeInputNotNullOutputVoid() {

    // Arrange
    final AddressForm objectUnderTest = new AddressForm();
    final String postcode = "Large";

    // Act
    objectUnderTest.setPostcode(postcode);

    // Method returns void, testing that no exception is thrown
  }
}
