package com.diffblue.demo.ecommerce.forms;

import com.diffblue.demo.ecommerce.forms.AddressForm;
import com.diffblue.demo.ecommerce.forms.CustomerForm;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

import java.lang.reflect.Method;

public class CustomerFormTest {

  @Rule public ExpectedException thrown = ExpectedException.none();
  @Rule public Timeout globalTimeout = new Timeout(10000);

  /* testedClasses: CustomerForm */
  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void constructorOutputVoid() {

    // Act, creating object to test constructor
    final CustomerForm objectUnderTest = new CustomerForm();

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getEmailOutputNull() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();

    // Act
    final String retval = objectUnderTest.getEmail();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getFirstNameOutputNull() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();

    // Act
    final String retval = objectUnderTest.getFirstName();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getLastNameOutputNull() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();

    // Act
    final String retval = objectUnderTest.getLastName();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getPhoneNumberOutputNull() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();

    // Act
    final String retval = objectUnderTest.getPhoneNumber();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getShippingAddressOutputNull() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();

    // Act
    final AddressForm retval = objectUnderTest.getShippingAddress();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setEmailInputNotNullOutputVoid() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();
    final String email = "Large";

    // Act
    objectUnderTest.setEmail(email);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setFirstNameInputNotNullOutputVoid() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();
    final String firstName = "Large";

    // Act
    objectUnderTest.setFirstName(firstName);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setLastNameInputNotNullOutputVoid() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();
    final String lastName = "Large";

    // Act
    objectUnderTest.setLastName(lastName);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setPhoneNumberInputNotNullOutputVoid() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();
    final String phoneNumber = "Large";

    // Act
    objectUnderTest.setPhoneNumber(phoneNumber);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setShippingAddressInputNotNullOutputVoid() {

    // Arrange
    final CustomerForm objectUnderTest = new CustomerForm();
    final AddressForm shippingAddressForm = new AddressForm();

    // Act
    objectUnderTest.setShippingAddress(shippingAddressForm);

    // Method returns void, testing that no exception is thrown
  }
}
