package com.diffblue.demo.ecommerce.forms;

import com.diffblue.deeptestutils.Reflector;
import com.diffblue.demo.ecommerce.forms.PaymentForm;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Date;

public class PaymentFormTest {

  @Rule public ExpectedException thrown = ExpectedException.none();
  @Rule public Timeout globalTimeout = new Timeout(10000);

  /* testedClasses: PaymentForm */
  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void constructorOutputVoid() {

    // Act, creating object to test constructor
    final PaymentForm objectUnderTest = new PaymentForm();

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getCardNumberOutputNull() {

    // Arrange
    final PaymentForm objectUnderTest = new PaymentForm();

    // Act
    final String retval = objectUnderTest.getCardNumber();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getCvvOutputNull() {

    // Arrange
    final PaymentForm objectUnderTest = new PaymentForm();

    // Act
    final String retval = objectUnderTest.getCvv();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getExpiryDateOutputNull() {

    // Arrange
    final PaymentForm objectUnderTest = new PaymentForm();

    // Act
    final Date retval = objectUnderTest.getExpiryDate();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getNameOnCardOutputNull() {

    // Arrange
    final PaymentForm objectUnderTest = new PaymentForm();

    // Act
    final String retval = objectUnderTest.getNameOnCard();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setCardNumberInputNotNullOutputVoid() {

    // Arrange
    final PaymentForm objectUnderTest = new PaymentForm();
    final String cardNumber = "Large";

    // Act
    objectUnderTest.setCardNumber(cardNumber);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setCvvInputNotNullOutputVoid() {

    // Arrange
    final PaymentForm objectUnderTest = new PaymentForm();
    final String cvv = "Large";

    // Act
    objectUnderTest.setCvv(cvv);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setExpiryDateInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final PaymentForm objectUnderTest = new PaymentForm();
    final Date expiryDate = (Date)Reflector.getInstance("java.util.Date");
    Reflector.setField(expiryDate, "fastTime", 0L);

    // Act
    objectUnderTest.setExpiryDate(expiryDate);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setNameOnCardInputNotNullOutputVoid() {

    // Arrange
    final PaymentForm objectUnderTest = new PaymentForm();
    final String nameOnCard = "Large";

    // Act
    objectUnderTest.setNameOnCard(nameOnCard);

    // Method returns void, testing that no exception is thrown
  }
}
