package com.diffblue.demo.tdd.models;

import org.junit.Assert;
import org.junit.rules.ExpectedException;
import org.junit.Test;

import java.lang.reflect.Array;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import com.diffblue.deeptestutils.CompareWithFieldList;
import com.diffblue.deeptestutils.Reflector;

public class ProductTest {

  @org.junit.Rule
  public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: Product */


  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 22 branch to line 22
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product__init__000_f2ab38764b954078() throws Throwable {

    com.diffblue.demo.tdd.models.Product instance;
    {
      /* Arrange */

      /* Act */
      /* Creating object to test constructor */
      instance = new com.diffblue.demo.tdd.models.Product();

      /* Method return type is void, or not expected to return */
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 119 branch to line 120
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_equals_000_45faa1be2d412c31() throws Throwable {

    boolean retval;
    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_1 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_1, "description", null);
      Reflector.setField(param_1, "price", 0.0);
      Reflector.setField(param_1, "id", 0);
      Reflector.setField(param_1, "name", null);
      Object obj = null;

      /* Act */
      retval = param_1.equals(obj);
    }
    {
      /* Assert result */
      Assert.assertEquals(false, retval);
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 119 branch to line 122
   * conditional line 122 branch to line 122
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_equals_001_a69b5ff1801b6eaf() throws Throwable {

    boolean retval;
    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_2 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_2, "description", null);
      Reflector.setField(param_2, "price", 0.0);
      Reflector.setField(param_2, "id", 0);
      Reflector.setField(param_2, "name", null);
      Object obj = (Object) Reflector.getInstance("java.lang.Object");

      /* Act */
      thrown.expect(ClassCastException.class);
      retval = param_2.equals(obj);

      /* Method return type is void, or not expected to return */
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 91 branch to line 91
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_getDescription_000_42f4617550497ba5() throws Throwable {

    String retval;
    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_2 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_2, "description", null);
      Reflector.setField(param_2, "price", 0.0);
      Reflector.setField(param_2, "id", 0);
      Reflector.setField(param_2, "name", "");

      /* Act */
      retval = param_2.getDescription();
    }
    {
      /* Assert result */
      Assert.assertEquals(null, retval);
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 60 branch to line 60
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_getId_000_13f0d5e4b0b9feff() throws Throwable {

    int retval;
    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_4 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_4, "description", "");
      Reflector.setField(param_4, "price", 0.0);
      Reflector.setField(param_4, "id", 0);
      Reflector.setField(param_4, "name", "");

      /* Act */
      retval = param_4.getId();
    }
    {
      /* Assert result */
      Assert.assertEquals(0, retval);
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 43 branch to line 43
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_getName_000_9c2bfb6a586d2642() throws Throwable {

    String retval;
    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_2 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_2, "description", "");
      Reflector.setField(param_2, "price", 0.0);
      Reflector.setField(param_2, "id", 0);
      Reflector.setField(param_2, "name", null);

      /* Act */
      retval = param_2.getName();
    }
    {
      /* Assert result */
      Assert.assertEquals(null, retval);
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 75 branch to line 75
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_getPrice_000_fdbf1170947d4aa0() throws Throwable {

    double retval;
    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_4 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_4, "description", "");
      Reflector.setField(param_4, "price", 0.0);
      Reflector.setField(param_4, "id", 0);
      Reflector.setField(param_4, "name", "");

      /* Act */
      retval = param_4.getPrice();
    }
    {
      /* Assert result */
      Assert.assertEquals(0.0, (double) retval, 0.0f);
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 106 branch to line 106
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_hashCode_000_756a88f1b58ba41f() throws Throwable {

    int retval;
    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_4 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_4, "description", "");
      Reflector.setField(param_4, "price", 0.0);
      Reflector.setField(param_4, "id", 0);
      Reflector.setField(param_4, "name", "");

      /* Act */
      retval = param_4.hashCode();
    }
    {
      /* Assert result */
      Assert.assertEquals(0, retval);
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 101 branch to line 101
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_setDescription_000_ba9d6062659da943() throws Throwable {

    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_1 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_1, "description", "");
      Reflector.setField(param_1, "price", 0.0);
      Reflector.setField(param_1, "id", 0);
      Reflector.setField(param_1, "name", "");
      String description = null;

      /* Act */
      param_1.setDescription(description);

      /* Method return type is void, or not expected to return */
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 71 branch to line 71
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_setId_000_6f63dc49ce306dae() throws Throwable {

    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_1 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_1, "description", "");
      Reflector.setField(param_1, "price", 0.0);
      Reflector.setField(param_1, "id", 0);
      Reflector.setField(param_1, "name", "");
      int newId = 0;

      /* Act */
      param_1.setId(newId);

      /* Method return type is void, or not expected to return */
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 54 branch to line 54
   * conditional line 54 branch to line 57
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_setName_000_c7fa7d30bd3cf292() throws Throwable {

    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_3 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_3, "description", "");
      Reflector.setField(param_3, "price", 0.0);
      Reflector.setField(param_3, "id", 0);
      Reflector.setField(param_3, "name", "");
      String newName = "";

      /* Act */
      param_3.setName(newName);

      /* Method return type is void, or not expected to return */
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 54 branch to line 54
   * conditional line 54 branch to line 55
   * conditional line 55 branch to line 55
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_setName_001_9b3d7aaa904ac7f5() throws Throwable {

    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_3 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_3, "description", "");
      Reflector.setField(param_3, "price", 0.0);
      Reflector.setField(param_3, "id", 0);
      Reflector.setField(param_3, "name", "");
      String newName = "?";

      /* Act */
      param_3.setName(newName);

      /* Method return type is void, or not expected to return */
    }
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 87 branch to line 87
   */

  @org.junit.Test
  public void com_diffblue_demo_tdd_models_Product_setPrice_000_a9e013f2b0b84d98() throws Throwable {

    {
      /* Arrange */
      com.diffblue.demo.tdd.models.Product param_1 = (com.diffblue.demo.tdd.models.Product) Reflector.getInstance("com.diffblue.demo.tdd.models.Product");
      Reflector.setField(param_1, "description", "");
      Reflector.setField(param_1, "price", 0.0);
      Reflector.setField(param_1, "id", 0);
      Reflector.setField(param_1, "name", "");
      double price = 0.0;

      /* Act */
      param_1.setPrice(price);

      /* Method return type is void, or not expected to return */
    }
  }
}
