package com.diffblue.demo.ecommerce.models;

import com.diffblue.deeptestutils.Reflector;
import com.diffblue.demo.ecommerce.models.Address;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class AddressTest {

  @Rule public ExpectedException thrown = ExpectedException.none();
  @Rule public Timeout globalTimeout = new Timeout(10000);

  /* testedClasses: Address */
  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void constructorInputNotNullNotNullNotNullNotNullNotNullOutputVoid() {

    // Arrange
    final String company = "Large";
    final String address = "Large";
    final String city = "Large";
    final String country = "Large";
    final String postcode = "Large";

    // Act, creating object to test constructor
    final Address objectUnderTest = new Address(company, address, city, country, postcode);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void constructorInputNotNullNotNullNotNullNotNullOutputVoid() {

    // Arrange
    final String address = "Large";
    final String city = "Large";
    final String country = "Large";
    final String postcode = "Large";

    // Act, creating object to test constructor
    final Address objectUnderTest = new Address(address, city, country, postcode);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getAddressLineOutputNull() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);

    // Act
    final String retval = objectUnderTest.getAddressLine();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getCityOutputNull() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);

    // Act
    final String retval = objectUnderTest.getCity();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getCompanyOutputNull() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);

    // Act
    final String retval = objectUnderTest.getCompany();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getCountryOutputNull() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);

    // Act
    final String retval = objectUnderTest.getCountry();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getIdOutputZero() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);

    // Act
    final int retval = objectUnderTest.getId();

    // Assert result
    Assert.assertEquals(0, retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getPostcodeOutputNull() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);

    // Act
    final String retval = objectUnderTest.getPostcode();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setAddressLineInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);
    final String addressLine = "Large";

    // Act
    objectUnderTest.setAddressLine(addressLine);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setCityInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);
    final String city = "Large";

    // Act
    objectUnderTest.setCity(city);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setCompanyInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);
    final String company = "Large";

    // Act
    objectUnderTest.setCompany(company);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setCountryInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);
    final String country = "Large";

    // Act
    objectUnderTest.setCountry(country);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setIdInputZeroOutputVoid() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);
    final int id = 0;

    // Act
    objectUnderTest.setId(id);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setPostcodeInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Address objectUnderTest =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    objectUnderTest.setCountry(null);
    objectUnderTest.setId(0);
    objectUnderTest.setPostcode(null);
    objectUnderTest.setCity(null);
    objectUnderTest.setCompany(null);
    objectUnderTest.setAddressLine(null);
    final String postcode = "Large";

    // Act
    objectUnderTest.setPostcode(postcode);

    // Method returns void, testing that no exception is thrown
  }
}
