package com.diffblue.demo.ecommerce.models;

import com.diffblue.deeptestutils.Reflector;
import com.diffblue.demo.ecommerce.models.Address;
import com.diffblue.demo.ecommerce.models.Order;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class OrderTest {

  @Rule public ExpectedException thrown = ExpectedException.none();
  @Rule public Timeout globalTimeout = new Timeout(10000);

  /* testedClasses: Order */
  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void constructorInputNotNullNotNullNotNullNotNullNotNullNotNullOutputVoid()
      throws InvocationTargetException {

    // Arrange
    final String orderRef = "Large";
    final String firstName = "Small";
    final String lastName = "Large";
    final String email = "Small";
    final String phoneNumber = "Large";
    final Address shippingAddress =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    shippingAddress.setCountry(null);
    shippingAddress.setId(0);
    shippingAddress.setPostcode(null);
    shippingAddress.setCity(null);
    shippingAddress.setCompany(null);
    shippingAddress.setAddressLine(null);

    // Act, creating object to test constructor
    final Order objectUnderTest =
        new Order(orderRef, firstName, lastName, email, phoneNumber, shippingAddress);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getEmailOutputNull() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);

    // Act
    final String retval = objectUnderTest.getEmail();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getFirstNameOutputNull() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);

    // Act
    final String retval = objectUnderTest.getFirstName();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getIdOutputZero() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);

    // Act
    final int retval = objectUnderTest.getId();

    // Assert result
    Assert.assertEquals(0, retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getLastNameOutputNull() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);

    // Act
    final String retval = objectUnderTest.getLastName();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getOrderRefOutputNull() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);

    // Act
    final String retval = objectUnderTest.getOrderRef();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getPhoneNumberOutputNull() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);

    // Act
    final String retval = objectUnderTest.getPhoneNumber();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void getShippingAddressOutputNull() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);

    // Act
    final Address retval = objectUnderTest.getShippingAddress();

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setEmailInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);
    final String email = "Large";

    // Act
    objectUnderTest.setEmail(email);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setFirstNameInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);
    final String firstName = "Large";

    // Act
    objectUnderTest.setFirstName(firstName);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setIdInputZeroOutputVoid() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);
    final int id = 0;

    // Act
    objectUnderTest.setId(id);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setLastNameInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);
    final String lastName = "Large";

    // Act
    objectUnderTest.setLastName(lastName);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setOrderRefInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);
    final String orderRef = "Large";

    // Act
    objectUnderTest.setOrderRef(orderRef);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setPhoneNumberInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);
    final String phoneNumber = "Large";

    // Act
    objectUnderTest.setPhoneNumber(phoneNumber);

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void setShippingAddressInputNotNullOutputVoid() throws InvocationTargetException {

    // Arrange
    final Order objectUnderTest =
        (Order)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Order");
    objectUnderTest.setLastName(null);
    objectUnderTest.setPhoneNumber(null);
    objectUnderTest.setOrderRef(null);
    objectUnderTest.setShippingAddress(null);
    objectUnderTest.setFirstName(null);
    objectUnderTest.setEmail(null);
    objectUnderTest.setId(0);
    final Address shippingAddress =
        (Address)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Address");
    shippingAddress.setCountry(null);
    shippingAddress.setId(0);
    shippingAddress.setPostcode(null);
    shippingAddress.setCity(null);
    shippingAddress.setCompany(null);
    shippingAddress.setAddressLine(null);

    // Act
    objectUnderTest.setShippingAddress(shippingAddress);

    // Method returns void, testing that no exception is thrown
  }
}
