package com.diffblue.demo.ecommerce.controllers;

import com.diffblue.deeptestutils.Reflector;
import com.diffblue.demo.ecommerce.models.Product;
import com.diffblue.demo.ecommerce.repositories.ProductRepository;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.util.ArrayList;
import javax.servlet.http.HttpSession;


public class CartControllerTest {

  @Rule
  public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/diffblue/demo/ecommerce/controllers/CartController.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void updateCart1() throws Throwable {

    // Setup mocks
    Product product = ((Product)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Product"));
    Reflector.setField(product, "price", 0.0);
    Reflector.setField(product, "sku", null);
    Reflector.setField(product, "id", 0);
    Reflector.setField(product, "collection", null);
    Reflector.setField(product, "name", null);
    Reflector.setField(product, "photo", null);
    Reflector.setField(product, "category", null);
    Reflector.setField(product, "size", null);
    Reflector.setField(product, "description", null);
    ArrayList productRepositorys = new ArrayList();

    // Arrange
    CartController objectUnderTest = ((CartController)Reflector.getInstance("com.diffblue.demo.ecommerce.controllers.CartController"));
    ProductRepository productRepository = ((ProductRepository)org.mockito.Mockito.mock(ProductRepository.class));
    Reflector.setField(objectUnderTest, "productRepo", productRepository);
    productRepositorys.add(productRepository);
    int productId = 0;
    int quantity = 0;
    HttpSession session = ((HttpSession)Reflector.getInstance("javax.servlet.http.HttpSession"));
    String size = "";
    org.mockito.Mockito.when(((com.diffblue.demo.ecommerce.repositories.ProductRepository)productRepository).findById(org.mockito.Matchers.anyInt()))
      .thenReturn(product);

    // Act
    String retval = objectUnderTest.updateCart(productId, quantity, session, size);

    // Assert result
    Assert.assertEquals("redirect:/cart", retval);

  }

  /* testedClasses: com/diffblue/demo/ecommerce/controllers/CartController.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void updateCart2() throws Throwable {

    // Setup mocks
    Product product = ((Product)Reflector.getInstance("com.diffblue.demo.ecommerce.models.Product"));
    Reflector.setField(product, "price", 0.0);
    Reflector.setField(product, "sku", null);
    Reflector.setField(product, "id", 0);
    Reflector.setField(product, "collection", null);
    Reflector.setField(product, "name", null);
    Reflector.setField(product, "photo", null);
    Reflector.setField(product, "category", null);
    Reflector.setField(product, "size", null);
    Reflector.setField(product, "description", null);
    ArrayList productRepositorys = new ArrayList();

    // Arrange
    CartController objectUnderTest = ((CartController)Reflector.getInstance("com.diffblue.demo.ecommerce.controllers.CartController"));
    ProductRepository productRepository = ((ProductRepository)org.mockito.Mockito.mock(ProductRepository.class));
    Reflector.setField(objectUnderTest, "productRepo", productRepository);
    productRepositorys.add(productRepository);
    int productId = 0;
    int quantity = 0;
    HttpSession session = ((HttpSession)Reflector.getInstance("javax.servlet.http.HttpSession"));
    String size = "";
    org.mockito.Mockito.when(((com.diffblue.demo.ecommerce.repositories.ProductRepository)productRepository).findById(org.mockito.Matchers.anyInt()))
        .thenReturn(product);

    // Act
    String retval = objectUnderTest.updateCart(productId, quantity, session, size);

    // Assert result
    Assert.assertEquals("redirect:/cart", retval);

  }
}
